---
- name: Backup current configs on php
  block:

  - name: Backup - make directory for backup at /etc/php/{{ php_version }}/.backup
    file:
      path: /etc/php/{{ php_version }}/.backup
      state: directory

  - name: Backup - create specific backup dir for this running
    file:
      path: /etc/php/{{ php_version }}/.backup/{{ ansible_date_time.iso8601 }}
      state: directory

  - name: Backup - create specific backup dir for php cli
    file:
      path: /etc/php/{{ php_version }}/.backup/{{ ansible_date_time.iso8601 }}/cli
      state: directory

  - name: Backup - create specific backup dir for php fpm
    file:
      path: /etc/php/{{ php_version }}/.backup/{{ ansible_date_time.iso8601 }}/fpm
      state: directory

  - name: Backup - backing up php cli
    command: cp /etc/php/{{ php_version }}/cli/php.ini /etc/php/{{ php_version }}/.backup/{{ ansible_date_time.iso8601 }}/cli/php.ini

  - name: Backup - backing up php fpm
    command: cp /etc/php/{{ php_version }}/fpm/pool.d/www.conf /etc/php/{{ php_version }}/.backup/{{ ansible_date_time.iso8601 }}/fpm/www.conf

- name: Config log directory at {{ php_log_dir }}
  file:
    path: "{{ php_log_dir }}"
    state: directory

- name: Override cli php.ini config
  template:
    src: "cli/php.ini.j2"
    dest: "/etc/php/{{ php_version }}/cli/php.ini"

- name: Override fpm configs
  template:
    src: "fpm/www.conf.j2"
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
  notify:
    - restart php-fpm service

- name: Debug ansible gathering facts on remote machine
  debug:
    var: ansible_facts
