---
- name: Install essential packages for preparing php
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - software-properties-common    # For adding PPA
      - libfcgi0ldbl                  # For direct request to php-fpm status

- name: Add ondrej PPA
  apt_repository:
    repo: ppa:ondrej/php

- name: Install php{{ php_version }} packages
  apt:
    name: "{{ php_default_packages + php_packages }}"
    state: present
  notify:
    - start php-fpm service
