---
- name: Install essential packages for preparing php
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - software-properties-common    # For adding PPA
      - libfcgi0ldbl                  # For direct request to php-fpm status

- name: Add ondrej PPA
  apt_repository:
    repo: ppa:ondrej/php

- name: Install php{{ php_version }} packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "php{{ php_version }}-common"
      - "php{{ php_version }}-cli"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-json"
      - "php{{ php_version }}-opcache"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-bcmath"
      - "php{{ php_version }}-tidy"
      - "php{{ php_version }}-zip"
      - "php{{ php_version }}-bz2"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-imap"
      - "php{{ php_version }}-readline"
      - "php{{ php_version }}-soap"
      - "php-apcu"
      - "php-mongo"
      - "php-mongodb"
      - "php-redis"
      - "php-xdebug"
      - "dh-php"
      # - "php{{ php_version }}-mcrypt"
      # Dropped mcrypt because of Deprecated
      # https://www.php.net/manual/en/migration71.deprecated.php#migration71.deprecated.ext-mcrypt
  notify:
    - start php-fpm service
