---
# handlers file for ansible-role-php
- name: start php-fpm service
  systemd:
    name: php{{ php_version }}-fpm
    state: started
    enabled: yes

- name: restart php-fpm service
  systemd:
    name: php{{ php_version }}-fpm
    daemon_reload: yes
    state: restarted

- name: reload php-fpm service
  systemd:
    name: php{{ php_version }}-fpm
    daemon_reload: yes
    state: reloaded
